
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-09
owner: ucsb-cs156-f25
repo_name: team02-f25-09
pull_requests: [{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dkim876-patch-1","number":120,"title":"Update README.md","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/120"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-organization-edit-page","number":118,"title":"DB-Organization Edits page and tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/118"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-diningcommonsmenuitems-navapp","number":117,"title":"fixed nav bar + app","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/117"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-edit-page","number":115,"title":"Dk help request edit page","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/115"}]
