
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-09
owner: ucsb-cs156-f25
repo_name: team02-f25-09
pull_requests: [{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-menuitems-form","number":77,"title":"UCSBDiningCommonsMenuItems form component","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/77"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-copy-files","number":76,"title":"DB - Finished Copying files","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/76"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-RecommendationRequests-tableComponent","number":75,"title":"lc - Table Component for RecommendationRequest plus tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/75"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-RecommendationRequests-formComponent","number":74,"title":"lc - Form Component for RecommendationRequest plus tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/74"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-RecommendationRequests-fixtures","number":73,"title":"lc - Create fixtures for RecommendationRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/73"},{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"menuitemreview-createfixtures","number":71,"title":"Added MenuItemReview fixtures (4th times the charm)","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/71"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-UCSBDiningCommonsMenuItems-create-fixtures","number":70,"title":"UCSB dining commons menu items create fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/70"}]
