
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-09
owner: ucsb-cs156-f25
repo_name: team02-f25-09
pull_requests: [{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oy-mir-tablecomponent","number":108,"title":"Added table component + tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/108"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-create-page-articles","number":106,"title":"Vik create page articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/106"},{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oy-mir-formcomponent","number":105,"title":"Added tests for Form Component, finally fixed stryker issues","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/105"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-RecommendationRequest-copyPlaceholders","number":104,"title":"lc - Copy Placeholders for RecommendationRequest pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/104"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-edit-age-articles","number":103,"title":"Vik edit page articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/103"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-create-page","number":102,"title":"Dk help request create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/102"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-placeholder-pages","number":100,"title":"Dk help request placeholder pages","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/100"}]
