
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-09
owner: ucsb-cs156-f25
repo_name: team02-f25-09
pull_requests: [{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oy-mir-newstart","number":112,"title":"stryker please (#38)","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/112"},{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oy-mir-tablecomponentswillwork","number":111,"title":"MenuItemReview table components running (passing on stryker)","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/111"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-index-page","number":109,"title":"Dk help request index page","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/109"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-create-page-articles","number":106,"title":"Vik create page articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/106"}]
