
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-09
owner: ucsb-cs156-f25
repo_name: team02-f25-09
pull_requests: [{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-form","number":86,"title":"dk - add form and test for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/86"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"viktorinkov-copy-files-for-backend","number":85,"title":"viktorinkov - copy backend CRUD operations from team01 for the articles table","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/85"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-commit-table","number":84,"title":"Db-commit(Organizations) table","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/84"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-UCSBDiningCommonsMenuItems-placeholders","number":83,"title":"SC-ucsb dining commons menu items-placeholders","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/83"}]
