
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-09
owner: ucsb-cs156-f25
repo_name: team02-f25-09
pull_requests: [{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-commit-table","number":84,"title":"Db-commit(Organizations) table","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/84"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-UCSBDiningCommonsMenuItems-placeholders","number":83,"title":"SC-ucsb dining commons menu items-placeholders","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/83"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-UCSBDiningCommonsMenuItems-table","number":82,"title":"UCSB dining commons menu items table","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/82"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-organization-form","number":81,"title":"Db-organization form","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/81"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-create-fixtures","number":80,"title":"Db create fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/80"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-helprequest-fixtures","number":79,"title":"dk - add javascript fixtures for HelpRequest table","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/79"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-menuitems-form","number":77,"title":"UCSBDiningCommonsMenuItems form component","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/77"}]
