
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-09
owner: ucsb-cs156-f25
repo_name: team02-f25-09
pull_requests: [{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-create-page","number":102,"title":"Dk help request create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/102"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-Organization-index-page","number":101,"title":"Db-organization index page","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/101"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-placeholder-pages","number":100,"title":"Dk help request placeholder pages","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/100"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-index-page-articles","number":99,"title":"Vik index page articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/99"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-copy-placeholder-articles","number":98,"title":"Vik copy placeholder articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/98"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-table-component-articles","number":97,"title":"Vik table component articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/97"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-Create-Organization-page","number":96,"title":"Db create organization page","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/96"}]
