
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-09
owner: ucsb-cs156-f25
repo_name: team02-f25-09
pull_requests: [{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-RecommendationRequest-web","number":154,"title":"lc - End 2 End Tests for RecommendationRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/154"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequests-e2e-tests","number":153,"title":"add e2e tests for HelpRequests","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/153"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-articles-e2e-tests","number":152,"title":"End to End tests for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-09/pull/152"}]
